# LISTEN_GEM_USE_POLLING=1 bundle exec jekyll serve --livereload --force_polling
title: Chengyan Tsai / Max
email: crescentmax@tamu.edu
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "https://crescentmax.github.io"  
baseurl: ""
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minimal-mistakes-jekyll
exclude:
  - minimal-mistakes
# remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: dark
plugins:
  - jekyll-feed
  - jekyll-include-cache
include: ["_pages"]

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      share: false
      related: true


year_archive:
  enabled: false

heading_anchors: false


footer:
  links:
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/chengyan-tsai-69b804225/"
      icon: "fab fa-linkedin" # FontAwesome icon class for LinkedIn
      target: _blank
    - label: "Itch.io"
      url: "https://crescentmax.itch.io/"
      icon: "fab fa-itch-io"  # FontAwesome icon class for itch.io
      target: _blank
    - label: "Twitter"
      url: "https://x.com/crescent_max"
      icon: "fab fa-twitter"  # FontAwesome icon class for Twitter
      target: _blank
    - label: "Email"
      url: "mailto:crescentmax@tamu.edu"
      icon: "fas fa-envelope" # FontAwesome icon class for Email
      target: _blank

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor
  
sass:
  silence_deprecations:
    - import
  sass_dir: _sass
  quiet_deps: true

destination: /home/max/PersonalPage/crescentmax/_site
